### ISSUE TITLE
List without table tl_member_to_group

### ISSUE THREAD

**Issue by Volker2014** [cliffparnitzky/BirthdayLister#3]
Hi Cliff,

i searched for a solution to list the birthday of members without using an extra link table.
The reason is that i sometimes update all members via ftp and updating the link table makes more effort and is redundant.
I modified your class ModuleBirthdayLister in that way, that the field 'groups' in the member table is used.
If you are interested to modify your extension, feel free to contact me.

Best regards
Volker

**Comment by cliffparnitzky** [comment]
Hi Volker,
die Tabelle `tl_member_to_group` kommt aus der abhängigen Erweiterung `[associategroups]`. Sie ermöglicht es eine performante Abfrage auf DB Ebene zu erstellen. der Weg über das Feld `groups` ist extrem ineffezient. Deshalb wurde der Weg so gewählt. Dieser Teil wird also auch Gründen des Designs nicht geändert.

Für deinen Fall müsstest du nach dem Update via FTP die Methode `AssociateGroups->syncAssociationTable('member')` aufrufen.
